opam-version: "2.0"
name: "yicesQS"
version: "0.1"
synopsis: "Yices-QS, an extension of Yices for quantified satisfiability"
description: "Yices-QS, an extension of Yices for quantified satisfiability"
maintainer: "Stephane Graham-Lengrand <stephane.graham-lengrand@csl.sri.com>"
authors: "Stephane Graham-Lengrand <stephane.graham-lengrand@csl.sri.com>"
license: "GPLv3"
homepage: "https://github.com/disteph/yicesQS"
bug-reports: "https://github.com/disteph/yicesQS/issues"
depends: [
  "ocaml" {>= "4.08"}
  "dune" {build}
  "ocamlfind" {build}
  "containers"  {>= "3.0.0"}
  "tracing"
  "timer"
  "tyre"
  "libpoly"
  "yices2_bindings"
]
pin-depends: [
  ["tracing.dev" "https://github.com/disteph/tracing/archive/refs/heads/main.zip"]
  ["timer.dev" "https://github.com/disteph/timer/archive/refs/heads/main.zip"]
  ["libpoly.0.2" "https://github.com/SRI-CSL/libpoly_ocaml_bindings/archive/refs/heads/main.zip"]
  ["yices2_bindings.0.2" "https://github.com/SRI-CSL/yices2_ocaml_bindings/archive/49f9c9eabddfe27b5f965e6e0913da8c5450578c.zip"]
]
build: [
  make "build"
]
